[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.6"

[workspace.dependencies]
# Logging and tracing facade
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Loading env from .env files
dotenv = "0.15.0"

[profile.release]
opt-level = 2
