[package]
name = "client"
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos.workspace = true 
console_error_panic_hook.workspace = true
wasm-bindgen = "0.2.92"