[package]
name = "client"
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos.workspace = true 
leptos_router.workspace = true
console_error_panic_hook.workspace = true
thiserror.workspace = true
gloo-net.workspace = true
serde.workspace = true

wasm-bindgen = "0.2.92"
shared = { path = "../shared" }