[package]
name = "service-worker"

[lib]
crate-type = ["cdylib", "rlib"]

[package.edition]
workspace = true

[package.version]
workspace = true

[dependencies]
shared = { path = "../shared" }
wasm-bindgen = "0.2.92"
