[package]
name = "service-worker"

[lib]
crate-type = ["cdylib", "rlib"]

[package.edition]
workspace = true

[package.version]
workspace = true

[dependencies]
shared = { path = "../shared" }
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = [ 
    "console", "FetchEvent",  "Request",  
    "ReadableStream",  "ReadableStreamDefaultReader", 
    "Headers",  "ResponseInit",  "Response", 
    "ServiceWorkerGlobalScope", "WorkerGlobalScope", 
    "WorkerLocation", "Clients",
] }
