#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# Script to amend the last deployed version. Deletes the current tag, amends the commit,
# recreates the tag and force pushes
# $1 overrides the tag message

readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); cd ..; pwd )";
cd $repo_dir

readonly deploy_branch=deploy;

readonly version=`cat Cargo.toml | sed -n '/^version *=* */{s///;s/^"//;s/"$//;p;}'`;
if [ "$version" == "" ]; then
    echo "Failed to extract version from Cargo.toml";
    exit 1;
fi

readonly tag="v${version}";
readonly tag_message="${1:-Release of ${tag}}";

read -r -p "About to delete, amend and force push tag \"${tag}\" with annotation \"${tag_message}\". Continue? [Y/n]" response
response=${response,,}    # tolower
if [[ "$response" =~ ^(yes|y|)$ ]]; then
    # Make sure we're on the right branch
    git checkout main
    # Delete the remote tag
    git push --delete origin "tags/${tag}"
    # Delete the local tag
    git tag --delete ${tag}
    # Update the comit
    git commit --no-verify -a --amend --no-edit
    # Re-create the tag
    git tag -a "${tag}" -m "${tag_message}"
    # Force push this branch
    git push --force
    # Push the new tag
    git push origin "tags/${tag}"
    
    # If we have a deploy branch, make sure that's up to date
    if git show-ref --quiet refs/heads/$deploy_branch; then
        git checkout $deploy_branch
        # Merge main into this branch
        git merge -X theirs -m "Amend last deploy" main 
        # Overwite the remote
        git push --force origin deploy
        # Go back to main
        git checkout main
    fi 
else 
    echo "Aborted"
fi