#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# Bumps the toolchain to the latest stable release

readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); cd ..; pwd )";
cd $repo_dir

readonly release_url="https://raw.githubusercontent.com/rust-lang/rust/master/RELEASES.md";
readonly release_date=`curl -s ${release_url} | grep 'Version' | head -n 1 | cut -d'(' -f2 | cut -d')' -f1`

cat >rust-toolchain.toml <<EOF
[toolchain]
channel = "stable-${release_date}"
EOF

echo "Bumped to ${release_date}"