#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# Script to increment the patch version, tag it and push it
# $1 is the tag comment. Defaults to something generic if not provided
# Set NOBUMP=true to skip bumping the version (for when it's already been changed)
# Set BUMP={major, minor, patch} to set the kind of bump to do. Defaults to patch

readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); cd ..; pwd )";
cd $repo_dir

RED='\033[0;31m'
NC='\033[0m' # No Color

if ! cargo test; then 
    >&2 echo -e "${RED}Failing tests detected. Aborting${NC}";
    exit 1;
fi

if ! cargo +nightly fmt -- --check >/dev/null; then
    >&2 echo -e "${RED}Run rust fmt. Aborting${NC}";
    exit 1;
fi

./scripts/deploy_skip_tests