#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# Script to increment the patch version, tag it and push it
# $1 is the tag comment. Defaults to something generic if not provided
# Set NOBUMP=true to skip bumping the version (for when it's already been changed)
# Set BUMP={major, minor, patch} to set the kind of bump to do. Defaults to patch

readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); cd ..; pwd )";
cd $repo_dir

RED='\033[0;31m'
NC='\033[0m' # No Color

warn() { echo -e "${RED}$@${NC}" >&2; }
die() { warn "$@"; exit 1; }

if ! cargo test; then 
    die "Failing tests detected. Aborting";
fi

if ! cargo +nightly fmt -- --check >/dev/null; then
    die "Run rust fmt. Aborting";
fi

if grep -rn "allow(unused" --include \*.rs crates/; then 
    warn "allow(unused..) found"

    if [ "${1:-}" == "-y" ]; then 
        response="y"
    else 
        read -r -p "Continue? [Y/n]" response
    fi
    
    response=${response,,}    # tolower
    
    if ! [[ "$response" =~ ^(yes|y|)$ ]]; then
        die "Aborting";
    fi
fi

./scripts/deploy_skip_tests $*