#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

RED='\033[0;31m'
NC='\033[0m' # No Color

if ! cargo +nightly fmt -- --check >/dev/null; then
    >&2 echo -e "${RED}Run rust fmt. Aborting${NC}";
    exit 1;
fi

if ! cargo test; then 
    >&2 echo -e "${RED}Failing tests detected. Aborting${NC}";
    exit 1;
fi
