#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# Purges all failed runs
# If $1 == "all" purges everything
# If FILTER is provided it replaces the existing filter (be careful!)

status="--status failure"
if [ "${1:-}" == "all" ]; then
    status=""
fi

if [ "${FILTER:-}" != "" ]; then 
    status=$FILTER
fi

repo=$(gh repo view --json nameWithOwner -q .nameWithOwner)
gh run list \
    --limit 1000 \
    $status \
    --json databaseId \
    -q '.[].databaseId' \
    | xargs \
        -IID sh -c "echo \"Deleting ID\" && gh api \
            \"repos/${repo}/actions/runs/ID\" \
            -X DELETE"