#!/usr/bin/env bash

# Exit when any command fails
set -o errexit

# Exit when an undeclared variable is used
set -o nounset

# Exit when a piped command returns a non-zero exit code
set -o pipefail

# Launches postcss in watch mode
# Set RELEASE=true to enable release mode

readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); cd ..; pwd )";
cd $repo_dir
source "${repo_dir}/scripts/export_node_path";

readonly assets_dir="crates/server/assets";

npm exec postcss -- \
    "${assets_dir}/css/main_input.css" \
    --output "${assets_dir}/css/main_output.css" \
    --watch