[package]
name = "shared"

[package.edition]
workspace = true

[package.version]
workspace = true

[dependencies]
thiserror = "1.0.58"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenv = { workspace = true }
cargo_toml = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }