[package]
name = "shared"
edition.workspace = true
version.workspace = true

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenv = { workspace = true }
cargo_toml = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }

thiserror = "1.0.58"