[package]
name = "shared"
edition.workspace = true
version.workspace = true

[features]
database = [ "rusqlite/serde_json", "serde_json", "exemplar", "sea-query", "sea-query-rusqlite", "uuid/v4", "webauthn-rs" ]

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
dotenv.workspace = true
cargo_toml.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
const_format.workspace = true

rusqlite = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

sea-query = { workspace = true, optional = true }
sea-query-rusqlite = { workspace = true, optional = true }
webauthn-rs = { workspace = true, optional = true }
# Reduce rusqlite boilerplate when se/de rusqlite stmts/rows
exemplar = { version = "0.9.0", optional = true }

uuid = { version = "1.0", features = [ "serde" ] }